//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EPES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EPES() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EP.EPES", typeof(EPES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码不能小于6位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000001 {
            get {
                return ResourceManager.GetString("EPESC0000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码太长，不能超过20位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000002 {
            get {
                return ResourceManager.GetString("EPESC0000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码中不能有空格，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000003 {
            get {
                return ResourceManager.GetString("EPESC0000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码中不能有特殊字符，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000004 {
            get {
                return ResourceManager.GetString("EPESC0000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码不能重复字符，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000005 {
            get {
                return ResourceManager.GetString("EPESC0000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码不能为连续字符，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000006 {
            get {
                return ResourceManager.GetString("EPESC0000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名和密码不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000007 {
            get {
                return ResourceManager.GetString("EPESC0000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string EPESC0000008 {
            get {
                return ResourceManager.GetString("EPESC0000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string EPESC0000009 {
            get {
                return ResourceManager.GetString("EPESC0000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名[{0}]存在空格，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000010 {
            get {
                return ResourceManager.GetString("EPESC0000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，请检查后重试。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000011 {
            get {
                return ResourceManager.GetString("EPESC0000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意: 密码无效,密码和登录的用户名相同,请修改密码。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000012 {
            get {
                return ResourceManager.GetString("EPESC0000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名和密码相同，不允许登陆系统。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000013 {
            get {
                return ResourceManager.GetString("EPESC0000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录的用户,强制修改密码。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000014 {
            get {
                return ResourceManager.GetString("EPESC0000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败， 密码不正确。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000015 {
            get {
                return ResourceManager.GetString("EPESC0000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败， 用户不存在。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000016 {
            get {
                return ResourceManager.GetString("EPESC0000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败， 用户暂时锁定。请稍后登录。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000017 {
            get {
                return ResourceManager.GetString("EPESC0000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，用户永久锁定。请联系管理人员。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000018 {
            get {
                return ResourceManager.GetString("EPESC0000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败， 用户无效。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000019 {
            get {
                return ResourceManager.GetString("EPESC0000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败， 数据库操作失败。  的本地化字符串。
        /// </summary>
        internal static string EPESC0000020 {
            get {
                return ResourceManager.GetString("EPESC0000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败， 系统内存错误。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000021 {
            get {
                return ResourceManager.GetString("EPESC0000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码过期,强制修改密码。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000022 {
            get {
                return ResourceManager.GetString("EPESC0000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除此用户的登录信息？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000023 {
            get {
                return ResourceManager.GetString("EPESC0000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string EPESC0000024 {
            get {
                return ResourceManager.GetString("EPESC0000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码输入错误,请重新输入。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000025 {
            get {
                return ResourceManager.GetString("EPESC0000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码和旧密码一样,请重新输入。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000026 {
            get {
                return ResourceManager.GetString("EPESC0000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码和用户名一样,请重新输入。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000027 {
            get {
                return ResourceManager.GetString("EPESC0000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不匹配,请重新输入。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000028 {
            get {
                return ResourceManager.GetString("EPESC0000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码失败。请重试。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000029 {
            get {
                return ResourceManager.GetString("EPESC0000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作模式 的本地化字符串。
        /// </summary>
        internal static string EPESC0000030 {
            get {
                return ResourceManager.GetString("EPESC0000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多步操作 的本地化字符串。
        /// </summary>
        internal static string EPESC0000032 {
            get {
                return ResourceManager.GetString("EPESC0000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000033 {
            get {
                return ResourceManager.GetString("EPESC0000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入信息不合法 的本地化字符串。
        /// </summary>
        internal static string EPESC0000034 {
            get {
                return ResourceManager.GetString("EPESC0000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面描述不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000035 {
            get {
                return ResourceManager.GetString("EPESC0000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子系统不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000036 {
            get {
                return ResourceManager.GetString("EPESC0000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名最多允许输入128位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000037 {
            get {
                return ResourceManager.GetString("EPESC0000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入2位以上的画面名！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000038 {
            get {
                return ResourceManager.GetString("EPESC0000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面描述最多允许输入80位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000039 {
            get {
                return ResourceManager.GetString("EPESC0000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态库必须由数字、字母或下划线加&apos;.DLL&apos;组成，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000040 {
            get {
                return ResourceManager.GetString("EPESC0000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩写最多允许输入10位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000041 {
            get {
                return ResourceManager.GetString("EPESC0000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标编号最多允许输入3位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000042 {
            get {
                return ResourceManager.GetString("EPESC0000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用方式最多允许输入1位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000043 {
            get {
                return ResourceManager.GetString("EPESC0000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用路径最多允许输入500位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000044 {
            get {
                return ResourceManager.GetString("EPESC0000044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取画面{0}的dllname失败 的本地化字符串。
        /// </summary>
        internal static string EPESC0000045 {
            get {
                return ResourceManager.GetString("EPESC0000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}载入失败 的本地化字符串。
        /// </summary>
        internal static string EPESC0000046 {
            get {
                return ResourceManager.GetString("EPESC0000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮描述不能超过75位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000047 {
            get {
                return ResourceManager.GetString("EPESC0000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮描述不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000048 {
            get {
                return ResourceManager.GetString("EPESC0000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名不能超过125位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000049 {
            get {
                return ResourceManager.GetString("EPESC0000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名不能超过125位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000050 {
            get {
                return ResourceManager.GetString("EPESC0000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入大于两位的按钮名！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000051 {
            get {
                return ResourceManager.GetString("EPESC0000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000052 {
            get {
                return ResourceManager.GetString("EPESC0000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名为F1-F12时操作类型才能选择“多步操作”！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000053 {
            get {
                return ResourceManager.GetString("EPESC0000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子节点数不能超过999！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000054 {
            get {
                return ResourceManager.GetString("EPESC0000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败：{0} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000055 {
            get {
                return ResourceManager.GetString("EPESC0000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功执行 的本地化字符串。
        /// </summary>
        internal static string EPESC0000056 {
            get {
                return ResourceManager.GetString("EPESC0000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台程序调用失败! {0} sqlcode is {1}{2} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000057 {
            get {
                return ResourceManager.GetString("EPESC0000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单步操作 的本地化字符串。
        /// </summary>
        internal static string EPESC0000058 {
            get {
                return ResourceManager.GetString("EPESC0000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取APPNAME信息错误：{0} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000061 {
            get {
                return ResourceManager.GetString("EPESC0000061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入失败 的本地化字符串。
        /// </summary>
        internal static string EPESC0000062 {
            get {
                return ResourceManager.GetString("EPESC0000062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string EPESC0000063 {
            get {
                return ResourceManager.GetString("EPESC0000063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制新增 的本地化字符串。
        /// </summary>
        internal static string EPESC0000064 {
            get {
                return ResourceManager.GetString("EPESC0000064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string EPESC0000065 {
            get {
                return ResourceManager.GetString("EPESC0000065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存盘 的本地化字符串。
        /// </summary>
        internal static string EPESC0000066 {
            get {
                return ResourceManager.GetString("EPESC0000066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        internal static string EPESC0000067 {
            get {
                return ResourceManager.GetString("EPESC0000067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增目录 的本地化字符串。
        /// </summary>
        internal static string EPESC0000068 {
            get {
                return ResourceManager.GetString("EPESC0000068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增成功 的本地化字符串。
        /// </summary>
        internal static string EPESC0000069 {
            get {
                return ResourceManager.GetString("EPESC0000069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消新增 的本地化字符串。
        /// </summary>
        internal static string EPESC0000070 {
            get {
                return ResourceManager.GetString("EPESC0000070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！请进入维护模式进行排序操作！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000071 {
            get {
                return ResourceManager.GetString("EPESC0000071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增失败 的本地化字符串。
        /// </summary>
        internal static string EPESC0000072 {
            get {
                return ResourceManager.GetString("EPESC0000072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本节点下所有子节点都会被删除，且无法恢复！确定删除节点 [{0}] ？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000073 {
            get {
                return ResourceManager.GetString("EPESC0000073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string EPESC0000074 {
            get {
                return ResourceManager.GetString("EPESC0000074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string EPESC0000075 {
            get {
                return ResourceManager.GetString("EPESC0000075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消删除 的本地化字符串。
        /// </summary>
        internal static string EPESC0000076 {
            get {
                return ResourceManager.GetString("EPESC0000076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行成功 的本地化字符串。
        /// </summary>
        internal static string EPESC0000077 {
            get {
                return ResourceManager.GetString("EPESC0000077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string EPESC0000079 {
            get {
                return ResourceManager.GetString("EPESC0000079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放弃 的本地化字符串。
        /// </summary>
        internal static string EPESC0000080 {
            get {
                return ResourceManager.GetString("EPESC0000080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点名不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000081 {
            get {
                return ResourceManager.GetString("EPESC0000081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点名不能超过128位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000082 {
            get {
                return ResourceManager.GetString("EPESC0000082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源描述不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000083 {
            get {
                return ResourceManager.GetString("EPESC0000083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源描述不能超过80位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000084 {
            get {
                return ResourceManager.GetString("EPESC0000084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库操作错误SQLCODE : {0} msg: {1} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000085 {
            get {
                return ResourceManager.GetString("EPESC0000085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALL: 无限制 的本地化字符串。
        /// </summary>
        internal static string EPESC0000086 {
            get {
                return ResourceManager.GetString("EPESC0000086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有该群组的查询权限！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000087 {
            get {
                return ResourceManager.GetString("EPESC0000087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string EPESC0000088 {
            get {
                return ResourceManager.GetString("EPESC0000088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修改群组资源权限，是否保存？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000089 {
            get {
                return ResourceManager.GetString("EPESC0000089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有群组的查询权限！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000090 {
            get {
                return ResourceManager.GetString("EPESC0000090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非维护模式下无法修改权限！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000091 {
            get {
                return ResourceManager.GetString("EPESC0000091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能对用户授权，请操作用户所属或所管理群组！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000092 {
            get {
                return ResourceManager.GetString("EPESC0000092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嵌套查询模式下不能修改权限！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000093 {
            get {
                return ResourceManager.GetString("EPESC0000093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先勾选按钮对应的画面！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000094 {
            get {
                return ResourceManager.GetString("EPESC0000094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不是该群组管理员，无权更改其权限！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000095 {
            get {
                return ResourceManager.GetString("EPESC0000095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子组的按钮权限仅供查询，不能修改！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000096 {
            get {
                return ResourceManager.GetString("EPESC0000096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择群组查询其有权限的资源 的本地化字符串。
        /// </summary>
        internal static string EPESC0000097 {
            get {
                return ResourceManager.GetString("EPESC0000097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入至少两位画面名！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000098 {
            get {
                return ResourceManager.GetString("EPESC0000098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询画面数量超出范围，请输入查询条件限制查询结果！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000099 {
            get {
                return ResourceManager.GetString("EPESC0000099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取资源代码信息错误！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000100 {
            get {
                return ResourceManager.GetString("EPESC0000100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择群组或用户查询其有权限的资源 的本地化字符串。
        /// </summary>
        internal static string EPESC0000101 {
            get {
                return ResourceManager.GetString("EPESC0000101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请给资源分配相应的权限！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000102 {
            get {
                return ResourceManager.GetString("EPESC0000102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修改资源群组权限，是否保存？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000103 {
            get {
                return ResourceManager.GetString("EPESC0000103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户{0}具有{1}的权限，该权限来源于以下群组： 的本地化字符串。
        /// </summary>
        internal static string EPESC0000104 {
            get {
                return ResourceManager.GetString("EPESC0000104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认组 的本地化字符串。
        /// </summary>
        internal static string EPESC0000105 {
            get {
                return ResourceManager.GetString("EPESC0000105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取用户管辖部门信息错误：{0} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000106 {
            get {
                return ResourceManager.GetString("EPESC0000106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALL:所有部门 的本地化字符串。
        /// </summary>
        internal static string EPESC0000107 {
            get {
                return ResourceManager.GetString("EPESC0000107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择子系统！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000108 {
            get {
                return ResourceManager.GetString("EPESC0000108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入两位查询字符 的本地化字符串。
        /// </summary>
        internal static string EPESC0000109 {
            get {
                return ResourceManager.GetString("EPESC0000109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录的用户无权限查看该群组下的成员！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000110 {
            get {
                return ResourceManager.GetString("EPESC0000110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择同级节点！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000111 {
            get {
                return ResourceManager.GetString("EPESC0000111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页/共{1}页 的本地化字符串。
        /// </summary>
        internal static string EPESC0000112 {
            get {
                return ResourceManager.GetString("EPESC0000112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该页有尚未保存的数据，确认翻页？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000113 {
            get {
                return ResourceManager.GetString("EPESC0000113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &quot;未选中行! 的本地化字符串。
        /// </summary>
        internal static string EPESC0000114 {
            get {
                return ResourceManager.GetString("EPESC0000114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化密码成功 的本地化字符串。
        /// </summary>
        internal static string EPESC0000115 {
            get {
                return ResourceManager.GetString("EPESC0000115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &quot;系统参数修改成功 的本地化字符串。
        /// </summary>
        internal static string EPESC0000116 {
            get {
                return ResourceManager.GetString("EPESC0000116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消系统参数修改 的本地化字符串。
        /// </summary>
        internal static string EPESC0000117 {
            get {
                return ResourceManager.GetString("EPESC0000117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功执行 sqlcode is {0} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000118 {
            get {
                return ResourceManager.GetString("EPESC0000118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台程序调用失败! {0} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000119 {
            get {
                return ResourceManager.GetString("EPESC0000119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化密码 的本地化字符串。
        /// </summary>
        internal static string EPESC0000120 {
            get {
                return ResourceManager.GetString("EPESC0000120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名必须是大写字母与数字的组合，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000121 {
            get {
                return ResourceManager.GetString("EPESC0000121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法选择“多步操作” 的本地化字符串。
        /// </summary>
        internal static string EPESC0000122 {
            get {
                return ResourceManager.GetString("EPESC0000122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮展示 的本地化字符串。
        /// </summary>
        internal static string EPESC0000123 {
            get {
                return ResourceManager.GetString("EPESC0000123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮提示 的本地化字符串。
        /// </summary>
        internal static string EPESC0000124 {
            get {
                return ResourceManager.GetString("EPESC0000124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组名不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000125 {
            get {
                return ResourceManager.GetString("EPESC0000125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组描述最多允许输入100位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000127 {
            get {
                return ResourceManager.GetString("EPESC0000127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组管理员不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000128 {
            get {
                return ResourceManager.GetString("EPESC0000128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000129 {
            get {
                return ResourceManager.GetString("EPESC0000129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号不能少于3位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000130 {
            get {
                return ResourceManager.GetString("EPESC0000130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号不能多于[{0}]位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000131 {
            get {
                return ResourceManager.GetString("EPESC0000131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文姓名不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000132 {
            get {
                return ResourceManager.GetString("EPESC0000132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文姓名不能多于20位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000133 {
            get {
                return ResourceManager.GetString("EPESC0000133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有效不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000134 {
            get {
                return ResourceManager.GetString("EPESC0000134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门标识不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000135 {
            get {
                return ResourceManager.GetString("EPESC0000135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效天数不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000136 {
            get {
                return ResourceManager.GetString("EPESC0000136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门号不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000137 {
            get {
                return ResourceManager.GetString("EPESC0000137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门号不能超过18位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000138 {
            get {
                return ResourceManager.GetString("EPESC0000138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门中文名称不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000139 {
            get {
                return ResourceManager.GetString("EPESC0000139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门中文名不能超过50位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000140 {
            get {
                return ResourceManager.GetString("EPESC0000140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上层部门不能超过50位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000141 {
            get {
                return ResourceManager.GetString("EPESC0000141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门标识不能超过2位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000142 {
            get {
                return ResourceManager.GetString("EPESC0000142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门管理员不能超过18位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000143 {
            get {
                return ResourceManager.GetString("EPESC0000143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000144 {
            get {
                return ResourceManager.GetString("EPESC0000144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取资源类型失败！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000146 {
            get {
                return ResourceManager.GetString("EPESC0000146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000147 {
            get {
                return ResourceManager.GetString("EPESC0000147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能超过128位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000148 {
            get {
                return ResourceManager.GetString("EPESC0000148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源类型不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000149 {
            get {
                return ResourceManager.GetString("EPESC0000149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源描述不能超过80位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000150 {
            get {
                return ResourceManager.GetString("EPESC0000150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询账套信息失败 的本地化字符串。
        /// </summary>
        internal static string EPESC0000151 {
            get {
                return ResourceManager.GetString("EPESC0000151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除账套[{0}]？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000152 {
            get {
                return ResourceManager.GetString("EPESC0000152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败，请检查后重试！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000153 {
            get {
                return ResourceManager.GetString("EPESC0000153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否取消关联账套[{0}]下的群组[{1}]？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000154 {
            get {
                return ResourceManager.GetString("EPESC0000154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请进入维护模式操作！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000155 {
            get {
                return ResourceManager.GetString("EPESC0000155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000156 {
            get {
                return ResourceManager.GetString("EPESC0000156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败：{0}，请检查后重试！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000157 {
            get {
                return ResourceManager.GetString("EPESC0000157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账套描述不能为空，请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000158 {
            get {
                return ResourceManager.GetString("EPESC0000158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账套名不能为空，请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000159 {
            get {
                return ResourceManager.GetString("EPESC0000159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否退出维护模式？ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000160 {
            get {
                return ResourceManager.GetString("EPESC0000160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态库不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000161 {
            get {
                return ResourceManager.GetString("EPESC0000161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子系统参数不正确！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000162 {
            get {
                return ResourceManager.GetString("EPESC0000162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名称不能为空！请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000163 {
            get {
                return ResourceManager.GetString("EPESC0000163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基准画面名称不能为空！请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000164 {
            get {
                return ResourceManager.GetString("EPESC0000164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基准画面名称不能超过80位！请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000165 {
            get {
                return ResourceManager.GetString("EPESC0000165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键码、关键码名称不能超过30位！请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000166 {
            get {
                return ResourceManager.GetString("EPESC0000166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名称不能超过80位！请重新输入 的本地化字符串。
        /// </summary>
        internal static string EPESC0000167 {
            get {
                return ResourceManager.GetString("EPESC0000167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除资源组:{0} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000168 {
            get {
                return ResourceManager.GetString("EPESC0000168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！请进入资源组维护模式操作！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000169 {
            get {
                return ResourceManager.GetString("EPESC0000169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子组权限仅供查询，不能修改！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000170 {
            get {
                return ResourceManager.GetString("EPESC0000170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组名不能超过127位，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000171 {
            get {
                return ResourceManager.GetString("EPESC0000171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时锁定监控时间不能为空 的本地化字符串。
        /// </summary>
        internal static string EPESC0000172 {
            get {
                return ResourceManager.GetString("EPESC0000172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时锁定错误次数不能为空 的本地化字符串。
        /// </summary>
        internal static string EPESC0000173 {
            get {
                return ResourceManager.GetString("EPESC0000173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久锁定监控时间不能为空 的本地化字符串。
        /// </summary>
        internal static string EPESC0000174 {
            get {
                return ResourceManager.GetString("EPESC0000174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久锁定错误次数不能为空 的本地化字符串。
        /// </summary>
        internal static string EPESC0000175 {
            get {
                return ResourceManager.GetString("EPESC0000175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时锁定持续时间不能为空 的本地化字符串。
        /// </summary>
        internal static string EPESC0000176 {
            get {
                return ResourceManager.GetString("EPESC0000176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改目录 的本地化字符串。
        /// </summary>
        internal static string EPESC0000177 {
            get {
                return ResourceManager.GetString("EPESC0000177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将画面挂于根目录下，请先建立子目录 的本地化字符串。
        /// </summary>
        internal static string EPESC0000178 {
            get {
                return ResourceManager.GetString("EPESC0000178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源组名不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000179 {
            get {
                return ResourceManager.GetString("EPESC0000179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源组描述信息不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000180 {
            get {
                return ResourceManager.GetString("EPESC0000180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选后将查询未分配到资源组的画面/按钮。支持画面名模糊匹配查询。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000181 {
            get {
                return ResourceManager.GetString("EPESC0000181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选后将查询未挂到菜单树上的画面。支持画面名模糊匹配查询。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000182 {
            get {
                return ResourceManager.GetString("EPESC0000182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选后将查询未分配到资源组的细部资源。支持资源名模糊匹配查询。 的本地化字符串。
        /// </summary>
        internal static string EPESC0000183 {
            get {
                return ResourceManager.GetString("EPESC0000183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用失败，错误消息[{0}] 的本地化字符串。
        /// </summary>
        internal static string EPESC0000184 {
            get {
                return ResourceManager.GetString("EPESC0000184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在账套{0}下，资源{1}未分配到任何资源组 的本地化字符串。
        /// </summary>
        internal static string EPESC0000185 {
            get {
                return ResourceManager.GetString("EPESC0000185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在账套{0}下，资源{1}已经分配到资源组: {2} 的本地化字符串。
        /// </summary>
        internal static string EPESC0000186 {
            get {
                return ResourceManager.GetString("EPESC0000186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效天数不能超过180天 的本地化字符串。
        /// </summary>
        internal static string EPESC0000187 {
            get {
                return ResourceManager.GetString("EPESC0000187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件信息 的本地化字符串。
        /// </summary>
        internal static string EPESC0000188 {
            get {
                return ResourceManager.GetString("EPESC0000188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮信息 的本地化字符串。
        /// </summary>
        internal static string EPESC0000189 {
            get {
                return ResourceManager.GetString("EPESC0000189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件名 的本地化字符串。
        /// </summary>
        internal static string EPESC0000190 {
            get {
                return ResourceManager.GetString("EPESC0000190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名 的本地化字符串。
        /// </summary>
        internal static string EPESC0000191 {
            get {
                return ResourceManager.GetString("EPESC0000191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属画面不能为空，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000192 {
            get {
                return ResourceManager.GetString("EPESC0000192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统群组下不可挂子组，请将角色用户直接添加到该组下！ 的本地化字符串。
        /// </summary>
        internal static string EPESC0000193 {
            get {
                return ResourceManager.GetString("EPESC0000193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面名称 的本地化字符串。
        /// </summary>
        internal static string EPESC0000194 {
            get {
                return ResourceManager.GetString("EPESC0000194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画面代码 的本地化字符串。
        /// </summary>
        internal static string EPESC0000195 {
            get {
                return ResourceManager.GetString("EPESC0000195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源组名 的本地化字符串。
        /// </summary>
        internal static string EPESC0000196 {
            get {
                return ResourceManager.GetString("EPESC0000196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员1 的本地化字符串。
        /// </summary>
        internal static string EPESC0000197 {
            get {
                return ResourceManager.GetString("EPESC0000197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员2 的本地化字符串。
        /// </summary>
        internal static string EPESC0000198 {
            get {
                return ResourceManager.GetString("EPESC0000198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能按钮 的本地化字符串。
        /// </summary>
        internal static string EPESC0000199 {
            get {
                return ResourceManager.GetString("EPESC0000199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源组代码 的本地化字符串。
        /// </summary>
        internal static string EPESC0000200 {
            get {
                return ResourceManager.GetString("EPESC0000200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上层部门号不能与部门号相同！若无上层部门，上层部门号可不填写 的本地化字符串。
        /// </summary>
        internal static string EPESC0000201 {
            get {
                return ResourceManager.GetString("EPESC0000201", resourceCulture);
            }
        }
    }
}
